export const SELECT_ROCKET = 'SELECT_ROCKET';
export const SELECT_LAUNCHES_BEGIN = 'SELECT_LAUNCHES_BEGIN';
export const SELECT_LAUNCHES_SUCCESS = 'SELECT_LAUNCHES_SUCCESS';
export const SELECT_LAUNCHES_FAILURE = 'SELECT_LAUNCHES_FAILURE';
export const SEARCH_LAUNCHES = 'SEARCH_LAUNCHES';